/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vctl_mainso_NdkCall */

#ifndef _Included_com_vctl_mainso_NdkCall
#define _Included_com_vctl_mainso_NdkCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vctl_mainso_NdkCall
 * Method:    trigger
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vctl_mainso_NdkCall_trigger
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
